// Code generated by jtd-codegen for TypeScript v0.2.1

export enum PlateauCatalogType {
  DefaultName = "フォルダ",
  DefaultName0 = "ユースケース",
  DefaultName1 = "ランドマーク情報",
  DefaultName2 = "公園情報",
  DefaultName3 = "内水浸水想定区域モデル",
  DefaultName4 = "土地利用モデル",
  DefaultName5 = "土砂災害警戒区域モデル",
  DefaultName6 = "建築物モデル",
  DefaultName7 = "植生モデル",
  DefaultName8 = "橋梁モデル",
  DefaultName9 = "汎用都市オブジェクトモデル",
  DefaultName10 = "津波浸水想定区域モデル",
  DefaultName11 = "洪水浸水想定区域モデル",
  DefaultName12 = "緊急輸送道路情報",
  DefaultName13 = "行政界情報",
  DefaultName14 = "道路モデル",
  DefaultName15 = "避難施設情報",
  DefaultName16 = "都市計画決定情報モデル",
  DefaultName17 = "都市設備モデル",
  DefaultName18 = "鉄道モデル",
  DefaultName19 = "鉄道情報",
  DefaultName20 = "鉄道駅情報",
  DefaultName21 = "高潮浸水想定区域モデル",
}

export enum PlateauCatalogTypeEn {
  Bldg = "bldg",
  Border = "border",
  Brid = "brid",
  EmergencyRoute = "emergency_route",
  Fld = "fld",
  Folder = "folder",
  Frn = "frn",
  Gen = "gen",
  Htd = "htd",
  Ifld = "ifld",
  Landmark = "landmark",
  Lsld = "lsld",
  Luse = "luse",
  Park = "park",
  Rail = "rail",
  Railway = "railway",
  Shelter = "shelter",
  Station = "station",
  Tnm = "tnm",
  Tran = "tran",
  Urf = "urf",
  Usecase = "usecase",
  Veg = "veg",
}

export interface PlateauCatalogConfigDaum {
  name: string;
  type: string;
  url: string;
  layer?: string[];
}

export interface PlateauCatalogConfig {
  data: PlateauCatalogConfigDaum[];
}

export enum PlateauCatalogFormat {
  Dtiles = "3dtiles",
  Csv = "csv",
  Czml = "czml",
  Geojson = "geojson",
  Gltf = "gltf",
  Gtfs = "gtfs",
  Mvt = "mvt",
  Tiles = "tiles",
  Tms = "tms",
  Wms = "wms",
}

export interface PlateauCatalog0 {
  id: string;
  name: string;
  pref: string;
  type: PlateauCatalogType;
  type_en: PlateauCatalogTypeEn;
  bldg_no_texture_url?: string;
  city?: string;
  city_code?: string;
  city_en?: string;
  config?: PlateauCatalogConfig;
  desc?: string;
  format?: PlateauCatalogFormat;
  itemId?: string;
  layers?: string[];
  openDataUrl?: string;
  order?: number;
  pref_code?: string;
  search_index?: string;
  type2?: string;
  type2_en?: string;
  url?: string;
  ward?: string;
  ward_code?: string;
  ward_en?: string;
  year?: number;
}

export type PlateauCatalog = PlateauCatalog0[];
