export * from './ColorMap'
export * from './types'

export { default as colorMapCividis } from './colorMaps/cividis'
export { default as colorMapCrest } from './colorMaps/crest'
export { default as colorMapFlare } from './colorMaps/flare'
export { default as colorMapIcefire } from './colorMaps/icefire'
export { default as colorMapInferno } from './colorMaps/inferno'
export { default as colorMapMagma } from './colorMaps/magma'
export { default as colorMapMako } from './colorMaps/mako'
export { default as colorMapPlasma } from './colorMaps/plasma'
export { default as colorMapPlateau } from './colorMaps/plateau'
export { default as colorMapRocket } from './colorMaps/rocket'
export { default as colorMapTurbo } from './colorMaps/turbo'
export { default as colorMapViridis } from './colorMaps/viridis'
export { default as colorMapVlag } from './colorMaps/vlag'
