export * from './ColorScheme'
export * from './types'

export { default as colorSchemeCividis } from './colorSchemes/cividis'
export { default as colorSchemeCrest } from './colorSchemes/crest'
export { default as colorSchemeFlare } from './colorSchemes/flare'
export { default as colorSchemeIcefire } from './colorSchemes/icefire'
export { default as colorSchemeInferno } from './colorSchemes/inferno'
export { default as colorSchemeMagma } from './colorSchemes/magma'
export { default as colorSchemeMako } from './colorSchemes/mako'
export { default as colorSchemePlasma } from './colorSchemes/plasma'
export { default as colorSchemeRocket } from './colorSchemes/rocket'
export { default as colorSchemeTurbo } from './colorSchemes/turbo'
export { default as colorSchemeViridis } from './colorSchemes/viridis'
export { default as colorSchemeVlag } from './colorSchemes/vlag'
