fragment PlateauMunicipality on PlateauMunicipality {
  id
  code
  name
}

fragment PlateauDataset on PlateauDataset {
  id
  type
  typeName
  name
  variants {
    format
    url
    name
    ... on PlateauBuildingDatasetVariant {
      version
      lod
      textured
    }
  }
}
