fragment PlateauMunicipality on PlateauMunicipality {
  id
  code
  name
  prefecture {
    id
    code
    name
  }
}

fragment PlateauDataset on PlateauDataset {
  id
  type
  typeName
  name
  data {
    format
    url
    name
    ... on PlateauBuildingDatasetDatum {
      version
      lod
      textured
    }
  }
}
