fragment PlateauPrefecture on PlateauPrefecture {
  id
  code
  name
}

fragment PlateauMunicipality on PlateauMunicipality {
  id
  code
  name
  parents {
    id
    type
    code
    name
  }
  prefecture {
    ...PlateauPrefecture
  }
}

fragment PlateauDatasetDatum on PlateauDatasetDatum {
  id
  format
  url
  name
  ... on PlateauBuildingDatasetDatum {
    version
    lod
    textured
  }
}

fragment PlateauDataset on PlateauDataset {
  id
  name
  type
  typeName
  data {
    ...PlateauDatasetDatum
  }
}

fragment PlateauDatasetDetail on PlateauDataset {
  ...PlateauDataset
  description
  municipality {
    ...PlateauMunicipality
  }
}

fragment EstatArea on EstatArea {
  id
  name
  address
  addressComponents
  bbox
}

fragment EstatAreaGeometry on EstatAreaGeometry {
  id
  geometry
}
