query municipalityDatasets(
  $municipalityCode: String!
  $includeTypes: [PlateauDatasetType!]
  $excludeTypes: [PlateauDatasetType!]
) {
  municipality(code: $municipalityCode) {
    ...PlateauMunicipality
    datasets(includeTypes: $includeTypes, excludeTypes: $excludeTypes) {
      ...PlateauDataset
    }
  }
}

query datasets(
  $municipalityCodes: [String!]
  $includeTypes: [PlateauDatasetType!]
  $excludeTypes: [PlateauDatasetType!]
) {
  datasets(
    municipalityCodes: $municipalityCodes
    includeTypes: $includeTypes
    excludeTypes: $excludeTypes
  ) {
    ...PlateauDataset
    municipality {
      ...PlateauMunicipality
    }
  }
}
