query municipalityDatasets(
  $municipalityCode: String!
  $includeTypes: [PlateauDatasetType!]
  $excludeTypes: [PlateauDatasetType!]
) {
  municipality(code: $municipalityCode) {
    ...PlateauMunicipality
    datasets(includeTypes: $includeTypes, excludeTypes: $excludeTypes) {
      ...PlateauDataset
    }
  }
}
