export const FIRESTORE_MODULE_OPTIONS = 'FIRESTORE_MODULE_OPTIONS'
export const FIRESTORE = 'FIRESTORE'
export const FIRESTORE_COLLECTION = 'FIRESTORE_COLLECTION'
export const FIRESTORE_COLLECTION_METADATA = 'FIRESTORE_COLLECTION_METADATA'
